ammarahm-ed/react-native-actions-sheet

index.d.ts
`defaultOverlayOpacity` has a default value and is marked as optional in the README, but the corresponding entry in the type definition makes it mandatory.
=> Optional `defaultOverlayOpacity` prop

src/index.js
To repro:
- Bump the `react-native-action-sheet` version to the latest in the example
- Run `yarn install`
- Run the app
- Open the action sheet
- Press the action sheet and drag up
=> Fix "Can't find variable: extraScroll" in 0.1.8

src/index.js, src/styles.js
A bit of cleanup:
- Remove `Animated.parallel` using only one animation (nothing to parallelize)
- Remove unused variables `this.opacity` and `this.containerOpacity`
- Use `React.createRef` as recommended in the [React doc](https://reactjs.org/docs/refs-and-the-dom.html):
=> Clean up code

package.json, src/index.js
For better control of when to show or hide modal, a `visible` argument is proposed for the `setModalVisible` method.
=> Add ability to explicitly show/hide modal

README.md, index.d.ts, package.json, src/index.js
Ran into a small issue using an input inside of the action sheet with something like a save button - after typing in the input the keyboard would disappear but not let my press carry through to the button - instead it simply closed the keyboard.  
To the best of my knowledge this is due to the ScrollView and the way it handles taps normally, but adding `keyboardWillPersistTaps` to the ScrollView allowed it to operate as expected for the user.
Instead of forcing it on all the time I created a new prop that would accept the same options `keyboardWillPersistTaps` does and allow the consumer to decide if they want it or not.  Should allow for maximum backwards compatibility and the flexibility to control the keyboard in any way I desire as a consumer.
I was a little unsure of the best prop …
=> feat(ActionSheet): new prop to allow keyboard to stay open on press when desired

src/index.js
React Native just added the statusBarTranslucent option to their modal to help the background more seamlessly blend with the status bar.
**Before**
**After**
=> Use translucent status bar on Android

package.json, src/index.js
In some cases, the previous screen that contains an action sheet may not be unmounted. In this case, if the current screen has an Input and if the user has focused the input, then the application crashes. Because the action sheet in the previous screen still listening to the keyboard event. This pull request fixes this problem.
=>  Fix crash problem that occurs if the focused input is not children of current view

src/index.js
Hello,
I noticed that the current PropType value for `keyboardShouldPersistTaps` does not match the RN docs.
currently, [keyboardShouldPersistTaps PropType](https://github.com/ammarahm-ed/react-native-actions-sheet/blob/9ec11bf/src/index.js#L792) is defined as:
```javascript
PropTypes.oneOf(["always", "default", "never"])
```
It does not match [official doc for ScrollView](https://reactnative.dev/docs/0.63/scrollview#keyboardshouldpersisttaps):
```javascript
enum('always', 'never', 'handled', false, true) // deprecation warning for `false` & `true`
```
This PR sets PropType to:
```javascript
PropTypes.oneOf(["always", "handled", "never"])
```
=> Fix keyboardShouldPersistTaps PropType

src/index.js
Thanks for a good component.
I use this library on iOS and Android.
It works well on iOS but The below error occurred on Android.
[Can't find variable 'async']
So i find the 'async' words and edit the 'mesure' function.
As a result, it works well on iOS and Android.
Was it a typo mistake? Anyway, Thanks :)
(PS)
'_showModal' function, i didn't edit that code. It is already edited when i forked.
=> Fix bug on android

src/index.tsx
From react native 0.65 on the removelistener() is going to be deprecated, this new code should resolve this issue
=> Remove deprecated removelistener() in favor of remove()

index.tsx
In my project I have an ActionSheetProvider which makes it easy for us to open an action sheet from everywhere. This works really good for us 💪
However when upgrading to the latest version I've noticed that the ActionSheetProps was no longere exported.
solves #131
=> Add missing export of ActionSheetProps

src/index.tsx, src/types.ts
Hello,
Here is PR that gives some control at least do we want when the keyboard is shown to have padding or not. If we have just one option what is the current case, we are very limited as some designs ( that we already faced ) do not need adjusting content when the keyboard is shown. It would be great if you can accept this prop addition so that we as consumers have more control.
=> Enable control of keyboard padding

src/hooks/use-scroll-handlers.ts, src/index.tsx, src/provider.tsx
This PR closes #201. The problem was that inside a modal, the safe area height is 0 and we were assuming that a 0 height meant that the size of the safe area wasn't still computed. With these changes, the safe area ref starts as undefined until we get the right size.
=> Fix opening sheet inside modal

src/index.tsx
Currently typescript gives this error if we call just `actionSheetRef.current?.hide()`:
```
Expected 1 arguments, but got 0.
```
Making `data` optional should fix it.
=> Make data optional in hide() to fix ts error

src/index.tsx
If the containerStyle is defined but doesnt have a paddingBottom or a padding, the function returns undefined crashing the app
=> Fix padding undefined

src/index.tsx
This makes `hide` on the ref behave as described in the documentation.
`ref.current?.hide({ confirmed: true });` will now successfully pass `{ confirmed: true }` as the data param, accessible from the `onClose` callback.
Useful for when you only have one sheet and you want to determine whether the customer has dismissed the popover or it has been force closed.
=> ref.hide fix: allow 'data' to be passed through to onClose

docs/pages/reference/actionsheet.mdx
The `ActionSheet` prop `initialSnapIndex` is incorrectly typed in the docs.
=> Docs: fix type on `initialSnapIndex`

src/index.tsx
This PR solves the issue: [#254](https://github.com/ammarahm-ed/react-native-actions-sheet/issues/254)
This Pull Request addresses the issue where the ActionSheet component's vertical position is not correctly calculated when the React Native screen is not the same height as the device. 
This occurs, for example, when the app uses Native navigation and the React Native view is shorter than the device height, causing a portion of the content to be shifted and hidden below.
The cause of the issue is that the height of the `<Root />` component is hardcoded with the device height here
https://github.com/ammarahm-ed/react-native-actions-sheet/blob/93cf9fc943cf9e30cbbb7d4b15a687d1f3fc040c/src/index.tsx#L939
This is not always the case since the React view can take a different height than the …
=> Correct vertical position of Actionsheet

src/index.tsx
Fixes the Issue of a sometimes appearing Bottom Space at the ActionSheet.
In this Image you see a big green space on the bottom of the Actionsheet, this appears sometimes on Android and Ios like this Issue told us: [https://github.com/ammarahm-ed/react-native-actions-sheet/issues/222](url)
By removing the `- safeMarginFromTop` it calculates the Actionsheet height correctly and the problem should be solved.
I tested it using version 0.8.29 on Android and Ios, on both Devices it was fixed.
> "react-native-actions-sheet": "^0.8.29",
=> fix: Bottom Space Problem on all devices

src/index.tsx, src/types.ts
Sorry but I was not able to find any templates for PR's on the docs/repo.
In an app we are developing at the company I work for, we need access to the GestureResponderEvent of the backdrop to know if we should change the focus to a underlying input, thus the need of the callback. I imagined it may be someone else's problem, so here is the solution that has been working for us and adds no side/unknown effects to the codebase.
=> Adds `onTouchBackdrop` to pass up the touch event on the backdrop

docs/pages/guides/meta.json, docs/pages/guides/migrate.mdx
I've made changes to the page title and navigation bar title in the `/guides/migrate` section to make them version independent.
Additionally, I've used H2 for the headings of each version's guide to ensure they appear in the navigation bar. 
By changing existing H2 tags to H3, headings have been removed from the navigation bar, but the links remain functional.
=> Improve migration guide structure

docs/pages/guides/background.mdx
`backgroundInteractionEnabled` is not enough on its own to allow the background interaction as it is right now. 
I am not sure whether this should actually be fixed in the code so that `isModal` is modified internally when `backgroundInteractionEnabled` is set to `true`. 
But it took me some time to realize that `isModal` prop was required to be set to `false` for the feature to work so I wanted to contribute this small change so that it is clearer for anyone else that comes into the docs seeking how to enable this.
=> Docs: Add isModal={false} requirement to the example for bg interaction

src/hooks/use-scroll-handlers.ts
On my project, ref is null before not null, so getBoundingClientRect throw error
=> ref can be null in web
